// Spanish///////////////////////////////////////////////////////////////////////////////////////////////////
const spanishNumbers = ['cero','uno', 'dos', 'tres', 'cuatro', 'cinco', 'seis', 'siete', 'ocho', 'nueve', 'diez', 'once', 'doce', 'trece', 'catorce', 'quince', 'diez y seis', 'diez y siete', 'diez y ocho', 'diez y nueve', 'veinte', 'veintiuno', 'veintidós', 'veintitrés', 'veinticuatro', 'veinticinco', 'veintiséis', 'veintisiete', 'veintiocho', 'veintinueve', 'treinta', 'cuarenta', 'cincuenta', 'sesenta', 'setenta', 'ochenta', 'noventa', 'cien', 'ciento uno', 'dos cientos', 'mil','un millón']
const spanishBasics = ['sí', 'no', 'quizás', 'por favor', 'muchas gracias', 'de nada', 'perdón', 'lo siento', 'un momento', 'está bien', 'no importa', 'buenos días', 'buenas tardes', 'buenas noches', 'buenas noches', 'señor', 'señora', 'señorita', 'adios', 'hasta luego', 'hasta mañana', '¿comprende usted?', 'Yo no comprendo', 'yo comprendo', '¿cómo?', '¿cómo se llama?', 'me llamo Chase', '¿cómo está usted?', '¿qué tal?', 'muy bien gracias', '¿y tú?']


// French//////////////////////////////////////////////////////////////////////////////////////////////////////////
const frenchNumbers = ['zéro', 'un', 'deux', 'trois', 'quatre', 'cinq', 'six', 'sept', 'huit', 'neuf', 'dix', 'onze', 'douze', 'treize', 'quatorze', 'quinze', 'seize', 'dix-sept', 'dix-huit', 'dix-neuf', 'vingt', 'vingt et un', 'vingt-deux', 'vingt-trois', 'vingt-quatre', 'vingt-cinq', 'vingt-six', 'vingt-sept', 'vingt-huit', 'vingt-neuf', 'trente', 'quarante', 'cinquante', 'soixante', 'soixante-dix', 'quatre-vingts', 'quatre-vingt-dix', 'cent', 'cent un', 'deux cents', 'mille', 'un million']
const frenchBasics = ['salut', 'oui', 'non', 'peut-être', 's’il vous plaît', 'merci beaucoup', 'de rien', 'excusez-moi', 'je suis désolé', 'un moment', 'd’accord', 'ce ne fait rien', 'bonjour', 'bonsoir', 'bonsoir', 'bonne nuit', 'monsieur', 'madame', 'madmoiselle', 'au revoir', 'à tout à l’heure', 'à demain', 'comprenez-vous?', 'je ne comprends pas', 'je comprends', 'qu’est-ce que vous avez dit?', 'comment vous appelez-vous?', 'je m’appelle Chase', 'comment allez-vous?', 'comment ça va?', 'très bien, merci', 'et vous?']

// Italian///////////////////////////////////////////////////////////////////////////////////////////////////////////////
const italianNumbers = ['zero', 'uno', 'due', 'tre', 'quattro', 'cinque', 'sei', 'sette', 'otto', 'nove', 'dieci', 'undici', 'dodici', 'tredici', 'quattrodici', 'quindici', 'sedici', 'diciassette', 'diciotto', 'diciannove', 'venti', 'ventuno', 'ventidue', 'ventitrè', 'ventiquattro', 'venticinque', 'ventisei', 'ventisette', 'ventotto', 'ventinove', 'trenta', 'quaranta', 'cinquanta', 'sessanta', 'settanta', 'ottanta', 'novanta', 'cento', 'centouno', 'duecento', 'mille', 'un milione']
const italianBasics = ['ciao', 'sì', 'no', 'forse', 'per piacere', 'mille grazie', 'prego', 'mi scusi', 'mi dispiace', 'un momento', 'va bene', 'non importa', 'buon giorno', 'buona sera', 'buona sera', 'buona notte', 'signorer', 'signora', 'signorina', 'arrivederci', 'ciao', 'a domani', 'capisce?', 'Non capisco', 'Capisco', 'che cosa ha detto ?', 'lei, scusi, come si chiama ?', 'mi chiamo Chase', 'come sta ?', 'come va ?', 'molto bene, grazie', 'e lei ?'];

// German/////////////////////////////////////////////////////////////////////////////////////////////////////////////////
const germanNumbers = ['null', 'eins', 'zwei', 'drei', 'vier', 'fünf', 'sechs', 'sieben', 'acht', 'neun', 'zehn', 'elf', 'zwölf', 'dreizehn', 'vierzehn', 'fünfzehn', 'sechzehn', 'siebzehn', 'achtzehn', 'neunzehn', 'zwanzig', 'einundzwanzig', 'zweiundzwanzig', 'dreiundzwanzig', 'vierundzwanzig', 'fünfundzwanzig', 'sechsundzwanzig', 'siebenundzwanzig', 'achtundzwanzig', 'neunundzwanzig', 'dreißig', 'vierzig', 'fünfzig', 'sechzig', 'siebzig', 'achtzig', 'neunzig', 'einhundert', 'hunderteins', 'zweihundert', 'eintausend', 'eine Million']
const germanBasics = ['hallo', 'ja', 'nein', 'viellicht', 'bitte', 'vielen dank', 'bitteh sehr', 'verzeihung', 'Es tut mir leid', 'Augenblick mal', 'Schon gut', 'Das macht nichts', 'Guten Morgen', 'Guten Tag', 'Guten Abent', 'Guten Nacht', 'Der Herr', 'Der Frau', 'Der Fräulein', 'Auf Wiedersehen', 'Bis später', 'Bis Morgen', 'Verstehen Sie ?', 'Ich verstehen nicht', 'Ich verstehe', 'Wie bitte ?', 'Wie heißen Sie?', 'Ich heiße Chase', '?', 'Wie geht es Ihnen?', 'Gut, danke', 'und Ihnen?']
